#!/bin/bash

set -euo pipefail

if [ -z "${dots:-}" ]; then
    echo "Error!: 'dots' env var is not set. Check possible areas causing issue:"
    echo "  - ~/.zprofile"
    echo "  - ~/.zshrc"
    echo "  - ~/.config/shell/vars"
    exit 1
fi

if [ ! -e "$HOME/org/journal.org" ]; then
    echo "Error!: 'journal.org' does not exist."
    exit 1
fi

gpg -e --recipient B9E26121718F7C78364850497602CBAF2CAE9A43 --recipient 9DA099AB28DD44B68C48950A814A355856D8FACA --output "$dots"/common/org/journal.org.gpg "$HOME"/org/journal.org

echo "Journal encrypted and placed in $dots/common/org"
