#+title: Dell Command Notes

* _Dell Command Integration Suite for Microsoft System Center_
** Information
The /Dell Command Integration Suite/ (DCIS) for /Microsoft System Center/ (SCCM) provides integration for all major /Dell Command/ system management applications.
** Prerequisites
- Compatible SCCM version is installed
- Windows PowerShell is installed and configured on the SCCM server
- .NET 4.8.0 or higher is enabled on the SCCM server
- A network configuration
** General Notes
- Supports Win 10/11 Pro/Ent. versions & Windows Server 2012, 2012 R2, 2016, 2019, and 2022.
- Minimum SCCM version is 2403/2409
- */Configuration Manager Plugin Extensions/* and */Intel vPro OOB Management Extensions/* are supported only on systems running Configuration Manager console.
** Configuring a Network Access Account
1. Launch Configuration Manager console
2. Locate and click *Administration*
3. Expand *Overview > Site Configuration*, and click *Sites*.
4. Right click the site that you want to configure, and then select *Configure Site Components > Software Distribution*. The *Software Distribution Components Properties* screen is displayed.
5. Click the *Network Access Account* tab.
6. Select the *Specify the account that accesses network locations* option, and then click *Set*.
7. Make a selection from the drop-down menu:
   - *Existing Account*--Use an existing account
     a. Select your user account.
     b. Click *OK*.
   - *New Account*--Add a new account
     a. Enter administrator credentials for accessing Configuration Manager from your client systems.
     b. Click *OK*.
8. Click *OK*.
** Installation
1. Go to https://dell.com/support/support/product-details/en-us/product/command-integration-suite/drivers
2. Download and run the installer for Dell Command | Integration Suite for System Center
3. Follow the installer instructions, and select *Complete Installation*.
** Managing and updating distribution points
1. Launch the Configuration Manager console.
2. Click Software Library.
3. Expand Overview > Application Management > Packages and click Dell Client Deployment
4. Right click Client Custom Reboot Script and click Distribute Content.
5. Click Next and follow the on-screen instructions to distribute content to the distribution points.
6. If the packages were not distributed while they were being created, repeat step 3 and step 4 to ensure that the client system can access the packages during an operating system installation.
* _Dell Command | Configure_
** Information
/Dell Command | Configure/ provides a Command-Line Interface (CLI) and Graphic User Interface (GUI) to configure various BIOS features for Precision, OptiPlex, and Latitude models.
** Downloading and Installing the Configuration Wizard
1. Navigate to [[https://dell.com/support/home/en-us][Dell's support website]]
2. Enter in any serial tag for the model you're downloading for
3. Search for it, which should bring up the device's support page
4. Choose Drivers & Downloads from the side-bar
5. Ensure you choose /All <MODEL>/ (i.e. /All OptiPlex Micro 7020/) instead of /This Device: <SERIAL TAG>/
6. For the /Category/, choose /Systems Management/
7. Expand all and find /Dell Command | Configure Application/
8. Download it
** Creating a BIOS Configuration
1. Open up the /Dell Command Configure Wizard/
2. Choose *Create Multiplatform Package* from the lefthand side
3. Click *Edit*
4. Start editing the BIOS settings you need configured. You'll click the drop down in the "Value to Set" column. *Make sure Apply Settings is checked.*
5. When you're done, I find it best to generate a report and export the config (.cctk) somewhere on your computer just in case so you have these settings for later.
   a. You can choose to save these unencrypted since we're storing them internally and we aren't storing sensitive credentials
6. Export the .EXE
7. Set the System and Setup passwords to /daytime/
8. Encrypt without Passphrase, continue
9. Name the file *multiplatform-YYYYMMDDHHmm* i.e. *multiplatform-202508060851*
10. Save it to //data/share/SOFTWARE/Dell/BIOS
** Importing a BIOS Configuration into SCCM
1. Navigate to the *Software Library*
2. Expand *Application Management*
3. Right click *Packages*
4. Select *Import Dell Command | Configure Package*
5. Choose *Specify the self contained executable (SCE) file to create the package*
6. Click *Next*
7. Specify the location of the executable you made in the _*Creating a BIOS Configuration*_ section
8. Select all distribution points
9. Leave the UNC destination path as default
10. Click *OK*
** Adding a BIOS Configuration to a Task Sequence
1. Create or find + edit the task sequence you want to add a BIOS configuration step to
2. Choose *Add > General > Run Command Line* to add the step
3. Position the step after *Restart in Windows PE* and title it *Configure BIOS*
4. In the command line section, enter *ConfigurationWrapper.bat*
5. Checkmark the *Package* box and choose the package you created in the _*Importing a BIOS Configuration into SCCM*_ section
6. In the *Options* tab, make sure you checkmark *Continue on error*
* _Dell Command | Intel vPro Out of Band_
** Information
The /Dell Command | Intel vPro Out of Band/ console extends Dell Client Command Suite's system management capabilities to out of band computers, computers that are offline or have inaccessible operating systems. It enables remote management of an endpoint's BIOS, wipe a device's hard drive, and simultaneously update multiple devices.
** (Stand-alone) Downloading and Installing
